authorization:
    jwt:
        expiration:
            days: 7
        secret: WriteHereYourSecretStringForTokenSigningCredentials
#logging:
#    level:
#        org:
#            hibernate:
 #               SQL: DEBUG
 #               type: TRACE
#server:
#    error:
#        include-message: always
#        include-stacktrace: never
spring:
    application:
        name: ACME Security Center
    # Mysql
    #datasource:
    #    password: password
    #    url: jdbc:mysql://localhost:3306/lc?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    #    username: root
    #jpa:
    #    hibernate:
    #        ddl-auto: update
    #    properties:
    #        hibernate:
    #            dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    # Postgresql
    datasource:
        driver-class-name: org.postgresql.Driver
        #    JDBC : SGDB :// HOST : PORT / DB
        url: jdbc:postgresql://localhost:5432/aos
        username: postgres
        password: postgres
        jpa:
            database: postgresql
            hibernate:
                ddl-auto: update
            show-sql: true
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
    swagger-ui:
        operations-sorter: alpha
        path: /swagger-ui.html
